version: '3.3'

services:
  neo4j:
    image: neo4j:5.16
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/rootroot
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"  # Neo4j Browser HTTP interface
      - "7687:7687"  # Bolt protocol port for database connections
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j/config:/conf  # Mount custom configuration folder

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:

