version: '3.3'
services:
  neo4j:
    image: neo4j:4.2.4
    hostname: neo4j
    container_name : neo4jtest
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
